### ISSUE TITLE
failed to add API key

### ISSUE THREAD

**Issue by KangtanC** [gabacode/chatPDF#2]
Traceback (most recent call last):
  File "/Users/aquaticdwarf/Downloads/chatPDF-main/main.py", line 99, in <module>
    ask(file)
  File "/Users/aquaticdwarf/Downloads/chatPDF-main/main.py", line 38, in ask
    llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003"))
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
  
  openai.api_key = os.environ["API_KEY"] = "sk-WHZSRVz1mFKtLVaY5TyET3BlbkFJmy9NknFoRcz00tnWJ"

**Comment by gabacode** [comment]
Closing for now, feel free to reopen if needed.

**Comment by KangtanC** [comment]
thank you very much, it's very helpful. The API key I've sent has deleted several numbers so it can't be used.
